# === Stage 53: Add command help text and usage examples ===
# Project: FitnessJournal
def print_help():
    """Print command help text and usage examples for FitnessJournal."""
    print("FitnessJournal - Workout Journal")
    print("=" * 40)
    print()
    print("Usage Examples:")
    print()
    print("1. Initialize a new journal:")
    print("   python fitness_journal.py init")
    print()
    print("2. Add a new routine:")
    print("   python fitness_journal.py add --routine 'Push Day'")
    print()
    print("3. Log a set:")
    print("   python fitness_journal.py log --routine 'Push Day' --exercise 'Bench Press' --sets '5x10,3x12,2x15'")
    print()
    print("4. View routines:")
    print("   python fitness_journal.py routines")
    print()
    print("5. View weekly summary:")
    print("   python fitness_journal.py weekly")
    print()
    print("6. View personal records:")
    print("   python fitness_journal.py records")
    print()
    print("7. Clear all data:")
    print("   python fitness_journal.py clear")
